package ankur.codegen.wasm;

import java.util.List;

// Renders an instruction list as WebAssembly text format (.wat) -- the human-readable form
// of a module, and the artifact a reader can actually check by eye against the Ankur source.
//
// Instructions are written in flat (post-order) form rather than folded s-expressions,
// because flat form is exactly one line per instruction and therefore lines up one-to-one
// with what WasmBinaryWriter emits for the same list.
public final class WatWriter {

    private WatWriter() {
    }

    public static String write(WasmModule module) {
        StringBuilder sb = new StringBuilder();
        sb.append(";; Generated by the Ankur compiler. Do not edit by hand.\n");
        sb.append(";; Assemble with: wat2wasm ").append(module.name()).append(".wat\n");
        sb.append("(module\n");

        sb.append("  ;; দেখাও is not something WebAssembly can do by itself: a module has no I/O.\n");
        sb.append("  ;; Printing is imported from the host (see the generated .mjs runner).\n");
        sb.append("  (import \"").append(WasmModule.HOST_MODULE).append("\" \"")
                .append(WasmModule.PRINT_INT).append("\" (func (param i32)))\n");
        sb.append("  (import \"").append(WasmModule.HOST_MODULE).append("\" \"")
                .append(WasmModule.PRINT_FLOAT).append("\" (func (param f64)))\n");
        sb.append("  (import \"").append(WasmModule.HOST_MODULE).append("\" \"")
                .append(WasmModule.PRINT_STRING).append("\" (func (param i32 i32)))\n");
        sb.append('\n');

        // A বাক্য is a (pointer, length) pair into this memory; the host reads the bytes back
        // out to print them, which is why the memory is exported too.
        sb.append("  (memory (export \"").append(WasmModule.MEMORY_EXPORT).append("\") ")
                .append(WasmModule.MEMORY_PAGES).append(")\n");
        if (module.data().length > 0) {
            sb.append("  (data (i32.const 0) \"").append(escapeData(module.data())).append("\")\n");
        }
        sb.append('\n');

        sb.append("  (func (export \"").append(WasmModule.ENTRY_POINT).append("\")\n");
        for (int i = 0; i < module.locals().size(); i++) {
            sb.append("    (local ").append(module.locals().get(i).watName).append(')');
            String comment = module.localComments().get(i);
            if (comment != null) {
                sb.append("  ;; ").append(comment);
            }
            sb.append('\n');
        }
        if (!module.locals().isEmpty()) {
            sb.append('\n');
        }
        writeAll(module.body(), 2, sb);
        sb.append("  )\n");
        sb.append(")\n");
        return sb.toString();
    }

    private static void writeAll(List<Instr> instructions, int indentLevel, StringBuilder sb) {
        for (Instr instr : instructions) {
            write(instr, indentLevel, sb);
        }
    }

    private static void write(Instr instr, int indentLevel, StringBuilder sb) {
        switch (instr) {
            case Instr.Op op -> line(indentLevel, op.mnemonic(), null, sb);
            case Instr.ConstI32 c -> line(indentLevel, "i32.const " + c.value(), null, sb);
            case Instr.ConstF64 c -> line(indentLevel, "f64.const " + c.value(), null, sb);
            // Locals are referred to by index, not by name: .wat identifiers may only contain
            // ASCII, so a Bangla name like যোগফল can only survive as a trailing comment.
            case Instr.LocalGet g -> line(indentLevel, "local.get " + g.index(), g.comment(), sb);
            case Instr.LocalSet s -> line(indentLevel, "local.set " + s.index(), s.comment(), sb);
            case Instr.Call c -> line(indentLevel, "call " + c.funcIndex(), c.name(), sb);
            case Instr.Br b -> line(indentLevel, "br " + b.depth(), null, sb);
            case Instr.BrIf b -> line(indentLevel, "br_if " + b.depth(), null, sb);
            case Instr.Block b -> {
                line(indentLevel, "block", null, sb);
                writeAll(b.body(), indentLevel + 1, sb);
                line(indentLevel, "end", null, sb);
            }
            case Instr.Loop l -> {
                line(indentLevel, "loop", null, sb);
                writeAll(l.body(), indentLevel + 1, sb);
                line(indentLevel, "end", null, sb);
            }
            case Instr.If i -> {
                line(indentLevel, i.result() == null ? "if" : "if (result " + i.result().watName + ")", null, sb);
                writeAll(i.thenBody(), indentLevel + 1, sb);
                if (i.elseBody() != null) {
                    line(indentLevel, "else", null, sb);
                    writeAll(i.elseBody(), indentLevel + 1, sb);
                }
                line(indentLevel, "end", null, sb);
            }
        }
    }

    // A .wat data string is a byte string, not a text string: every byte outside printable
    // ASCII is written as a \XX escape. Bangla text is multi-byte UTF-8, so in practice almost
    // all of it comes out escaped -- which is correct, and is what wat2wasm expects.
    private static String escapeData(byte[] data) {
        StringBuilder sb = new StringBuilder();
        for (byte b : data) {
            int value = b & 0xFF;
            if (value == '"' || value == '\\') {
                sb.append('\\').append((char) value);
            } else if (value >= 0x20 && value < 0x7F) {
                sb.append((char) value);
            } else {
                sb.append('\\').append(String.format("%02x", value));
            }
        }
        return sb.toString();
    }

    private static void line(int indentLevel, String text, String comment, StringBuilder sb) {
        sb.append("  ".repeat(indentLevel)).append(text);
        if (comment != null) {
            sb.append("  ;; ").append(comment);
        }
        sb.append('\n');
    }
}
