package ankur.codegen;

import ankur.parser.ast.AssignStmt;
import ankur.parser.ast.BinaryExpr;
import ankur.parser.ast.BinaryOp;
import ankur.parser.ast.BlockStmt;
import ankur.parser.ast.Expr;
import ankur.parser.ast.IdentifierExpr;
import ankur.parser.ast.IfStmt;
import ankur.parser.ast.NumberLiteral;
import ankur.parser.ast.PrintStmt;
import ankur.parser.ast.Program;
import ankur.parser.ast.Stmt;
import ankur.parser.ast.UnaryExpr;
import ankur.parser.ast.UnaryOp;
import ankur.parser.ast.VarDeclStmt;
import ankur.parser.ast.VarType;
import ankur.parser.ast.WhileStmt;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.HashMap;
import java.util.Map;

// Translates a semantically-valid Ankur AST into Java source text. Assumes the program
// already passed SemanticAnalyzer with no errors -- this class does no validation of its own.
public final class JavaCodeGenerator {

    private final Deque<Map<String, String>> scopes = new ArrayDeque<>();
    private int nameCounter = 0;

    public String generate(Program program, String className) {
        scopes.push(new HashMap<>());

        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by the Ankur compiler. Do not edit by hand.\n");
        sb.append("public final class ").append(className).append(" {\n");
        sb.append("    public static void main(String[] args) {\n");
        for (Stmt stmt : program.statements()) {
            genStmt(stmt, 2, sb);
        }
        sb.append("    }\n");
        // Ankur accepts Bangla-Indic and ASCII digits equally on the way in (see Lexer); this
        // keeps the output side matching by rendering every printed number back out in
        // Bangla-Indic digits, so a fully-Bangla program reads as fully Bangla end to end.
        sb.append("\n    private static String bnDigits(Object value) {\n");
        sb.append("        StringBuilder out = new StringBuilder();\n");
        sb.append("        for (char c : String.valueOf(value).toCharArray()) {\n");
        sb.append("            out.append(c >= '0' && c <= '9' ? (char) ('\\u09E6' + (c - '0')) : c);\n");
        sb.append("        }\n");
        sb.append("        return out.toString();\n");
        sb.append("    }\n");
        sb.append("}\n");

        scopes.pop();
        return sb.toString();
    }

    private void genStmt(Stmt stmt, int indentLevel, StringBuilder sb) {
        switch (stmt) {
            case VarDeclStmt v -> {
                // Every declaration is generated with an explicit initializer (defaulting to
                // 0 / 0.0 when Ankur left it out) so Java's definite-assignment check always
                // passes, even for a variable Ankur allows to be declared without one.
                String javaName = declare(v.name());
                indent(indentLevel, sb);
                sb.append(javaType(v.type())).append(' ').append(javaName).append(" = ");
                if (v.initializer() != null) {
                    genExpr(v.initializer(), sb);
                } else {
                    sb.append(v.type() == VarType.PURNO ? "0" : "0.0");
                }
                sb.append(";\n");
            }
            case AssignStmt a -> {
                indent(indentLevel, sb);
                sb.append(resolve(a.name())).append(" = ");
                genExpr(a.value(), sb);
                sb.append(";\n");
            }
            case PrintStmt p -> {
                indent(indentLevel, sb);
                sb.append("System.out.println(bnDigits(");
                genExpr(p.value(), sb);
                sb.append("));\n");
            }
            case IfStmt i -> {
                indent(indentLevel, sb);
                sb.append("if (");
                genExpr(i.condition(), sb);
                sb.append(") {\n");
                genBlockBody(i.thenBranch(), indentLevel + 1, sb);
                indent(indentLevel, sb);
                if (i.elseBranch() != null) {
                    sb.append("} else {\n");
                    genBlockBody(i.elseBranch(), indentLevel + 1, sb);
                    indent(indentLevel, sb);
                }
                sb.append("}\n");
            }
            case WhileStmt w -> {
                indent(indentLevel, sb);
                sb.append("while (");
                genExpr(w.condition(), sb);
                sb.append(") {\n");
                genBlockBody(w.body(), indentLevel + 1, sb);
                indent(indentLevel, sb);
                sb.append("}\n");
            }
            case BlockStmt b -> genBlockBody(b, indentLevel, sb);
        }
    }

    // Ankur allows a nested block to redeclare (shadow) an outer name, but Java rejects
    // redeclaring any name still lexically in scope. Every declaration therefore gets a
    // fresh, globally-unique Java name (see declare/resolve) instead of reusing the Ankur
    // name directly, so shadowed Ankur programs still produce compilable Java.
    private void genBlockBody(BlockStmt block, int indentLevel, StringBuilder sb) {
        scopes.push(new HashMap<>());
        for (Stmt stmt : block.statements()) {
            genStmt(stmt, indentLevel, sb);
        }
        scopes.pop();
    }

    private void genExpr(Expr expr, StringBuilder sb) {
        switch (expr) {
            case NumberLiteral n ->
                    sb.append(n.isFloat() ? String.valueOf(n.floatValue()) : String.valueOf(n.intValue()));
            case IdentifierExpr id -> sb.append(resolve(id.name()));
            case BinaryExpr b -> {
                sb.append('(');
                genExpr(b.left(), sb);
                sb.append(' ').append(javaOperator(b.op())).append(' ');
                genExpr(b.right(), sb);
                sb.append(')');
            }
            case UnaryExpr u -> {
                sb.append('(').append(javaOperator(u.op()));
                genExpr(u.operand(), sb);
                sb.append(')');
            }
        }
    }

    private String declare(String ankurName) {
        String javaName = "v_" + ankurName + "_" + nameCounter++;
        scopes.peek().put(ankurName, javaName);
        return javaName;
    }

    private String resolve(String ankurName) {
        for (Map<String, String> scope : scopes) {
            String found = scope.get(ankurName);
            if (found != null) {
                return found;
            }
        }
        throw new IllegalStateException(
                "Unresolved identifier '" + ankurName + "' during code generation "
                        + "(the program should have been validated by SemanticAnalyzer first)");
    }

    private static void indent(int level, StringBuilder sb) {
        sb.append("    ".repeat(level));
    }

    private static String javaType(VarType type) {
        return type == VarType.PURNO ? "int" : "double";
    }

    private static String javaOperator(BinaryOp op) {
        return switch (op) {
            case ADD -> "+";
            case SUB -> "-";
            case MUL -> "*";
            case DIV -> "/";
            case MOD -> "%";
            case EQ -> "==";
            case NEQ -> "!=";
            case LT -> "<";
            case GT -> ">";
            case LE -> "<=";
            case GE -> ">=";
            case AND -> "&&";
            case OR -> "||";
        };
    }

    private static String javaOperator(UnaryOp op) {
        return switch (op) {
            case NEG -> "-";
            case POS -> "+";
            case NOT -> "!";
        };
    }
}
