package ankur.codegen;

import ankur.codegen.wasm.WasmModule;

// Emits the small JavaScript host that runs a generated .wasm module.
//
// This is not a second compiler target: a WebAssembly module is pure computation with no I/O
// at all, so দেখাও has to be supplied from outside. Shipping the host alongside the module is
// what makes the WebAssembly output runnable by itself, the same way the Java target needs
// nothing but a JVM.
public final class NodeRunnerGenerator {

    private NodeRunnerGenerator() {
    }

    public static String generate(String moduleName) {
        return """
                // Generated by the Ankur compiler. Do not edit by hand.
                // Run with:  node %1$s.mjs
                import { readFile } from "node:fs/promises";

                // Ankur reads Bangla-Indic and ASCII digits alike, and prints in Bangla-Indic.
                const banglaDigits = (text) =>
                    String(text).replace(/[0-9]/g, (d) => String.fromCharCode(0x09E6 + Number(d)));

                // A whole দশমিক value keeps its decimal point (২.০, not ২) so that the output
                // matches what the Java target prints for the same program.
                const doshomik = (value) =>
                    Number.isInteger(value) ? value.toFixed(1) : String(value);

                // A বাক্য reaches the host as a pointer and a length into the module's memory,
                // because WebAssembly has no string type -- so the bytes are read back out and
                // decoded here. Its digits are left alone: it is the author's own text.
                let memory;
                const decoder = new TextDecoder();
                const bakko = (pointer, length) =>
                    decoder.decode(new Uint8Array(memory.buffer, pointer, length));

                const bytes = await readFile(new URL("./%1$s.wasm", import.meta.url));
                const { instance } = await WebAssembly.instantiate(bytes, {
                    "%2$s": {
                        "%3$s": (value) => console.log(banglaDigits(value)),
                        "%4$s": (value) => console.log(banglaDigits(doshomik(value))),
                        "%5$s": (pointer, length) => console.log(bakko(pointer, length)),
                    },
                });

                memory = instance.exports["%6$s"];
                instance.exports["%7$s"]();
                """.formatted(
                moduleName,
                WasmModule.HOST_MODULE,
                WasmModule.PRINT_INT,
                WasmModule.PRINT_FLOAT,
                WasmModule.PRINT_STRING,
                WasmModule.MEMORY_EXPORT,
                WasmModule.ENTRY_POINT);
    }
}
