package ankur.codegen;

import ankur.parser.ast.AssignStmt;
import ankur.parser.ast.BinaryExpr;
import ankur.parser.ast.BinaryOp;
import ankur.parser.ast.BlockStmt;
import ankur.parser.ast.Expr;
import ankur.parser.ast.IdentifierExpr;
import ankur.parser.ast.IfStmt;
import ankur.parser.ast.NumberLiteral;
import ankur.parser.ast.PrintStmt;
import ankur.parser.ast.Program;
import ankur.parser.ast.Stmt;
import ankur.parser.ast.StringLiteral;
import ankur.parser.ast.UnaryExpr;
import ankur.parser.ast.UnaryOp;
import ankur.parser.ast.VarDeclStmt;
import ankur.parser.ast.VarType;
import ankur.parser.ast.WhileStmt;
import ankur.semantic.Type;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

// Translates a semantically-valid Ankur AST into Python 3 source. The course allows either
// Java or Python as the target language; emitting both is what lets the same program be shown
// running on two completely different runtimes.
//
// Python is the easiest of the three targets structurally -- it has if/else, while and
// arbitrary-precision integers -- but it gets two things wrong for Ankur by default, and both
// need the analyzer's types to fix:
//
//   1. `/` in Python is always float division. পূর্ণ / পূর্ণ must be integer division, so it
//      is emitted as `//` when both operands are পূর্ণ.
//   2. Python has no block scope at all: a name assigned inside an `if` is the same variable
//      as one outside it. Ankur allows a nested block to shadow an outer name, so a
//      declaration that actually does that gets renamed -- exactly as in the Java target, and
//      for the same reason -- while an ordinary, non-shadowing declaration (almost every
//      declaration in a real program) keeps the author's own name, so the generated Python
//      reads like the Ankur source instead of a wall of synthetic identifiers.
public final class PythonCodeGenerator {

    private final Map<Expr, Type> types;
    private final Deque<Map<String, String>> scopes = new ArrayDeque<>();
    private int nameCounter = 0;

    // `expressionTypes` comes from SemanticAnalyzer.expressionTypes().
    public PythonCodeGenerator(Map<Expr, Type> expressionTypes) {
        this.types = expressionTypes;
    }

    public String generate(Program program) {
        scopes.push(new HashMap<>());

        StringBuilder sb = new StringBuilder();
        sb.append("# -*- coding: utf-8 -*-\n");
        sb.append("# Generated by the Ankur compiler. Do not edit by hand.\n");
        sb.append("# Target: Python 3\n");
        sb.append("import sys\n\n");
        // Same Bangla-on-Windows problem as the other two targets: a console that is not UTF-8
        // cannot print Bangla script at all, and Python raises rather than substituting '?'.
        sb.append("if hasattr(sys.stdout, \"reconfigure\"):\n");
        sb.append("    sys.stdout.reconfigure(encoding=\"utf-8\")\n\n");
        sb.append("""
                def bn(value):
                    \"""Prints numbers in Bangla-Indic digits, as the Ankur source wrote them.\"""
                    return "".join(chr(0x09E6 + int(c)) if c.isdigit() else c for c in str(value))


                """);

        if (program.statements().isEmpty()) {
            sb.append("pass\n");
        }
        for (Stmt stmt : program.statements()) {
            genStmt(stmt, 0, sb);
        }

        scopes.pop();
        return sb.toString();
    }

    private void genStmt(Stmt stmt, int indentLevel, StringBuilder sb) {
        switch (stmt) {
            case VarDeclStmt v -> {
                // Generated before the name is declared, so a shadowing declaration's
                // initializer still reads the outer variable (see JavaCodeGenerator).
                String initializer = v.initializer() != null
                        ? genExpr(v.initializer())
                        : defaultValue(v.type());
                indent(indentLevel, sb);
                sb.append(declare(v.name())).append(" = ").append(initializer).append('\n');
            }
            case AssignStmt a -> {
                indent(indentLevel, sb);
                sb.append(resolve(a.name())).append(" = ").append(genExpr(a.value())).append('\n');
            }
            case PrintStmt p -> {
                indent(indentLevel, sb);
                // A বাক্য prints as written; converting its digits would rewrite the author's
                // own text, so only numbers go through bn().
                boolean isString = types.get(p.value()) == Type.STRING;
                sb.append("print(").append(isString ? genExpr(p.value()) : "bn(" + genExpr(p.value()) + ")")
                        .append(")\n");
            }
            case IfStmt i -> {
                indent(indentLevel, sb);
                sb.append("if ").append(genExpr(i.condition())).append(":\n");
                genBlockBody(i.thenBranch(), indentLevel + 1, sb);
                if (i.elseBranch() != null) {
                    indent(indentLevel, sb);
                    sb.append("else:\n");
                    genBlockBody(i.elseBranch(), indentLevel + 1, sb);
                }
            }
            case WhileStmt w -> {
                indent(indentLevel, sb);
                sb.append("while ").append(genExpr(w.condition())).append(":\n");
                genBlockBody(w.body(), indentLevel + 1, sb);
            }
            case BlockStmt b -> genBlockBody(b, indentLevel, sb);
        }
    }

    // Python takes its block structure from indentation, so an empty Ankur block would leave
    // a dangling `if ...:` with nothing under it. `pass` is the placeholder that keeps it valid.
    private void genBlockBody(BlockStmt block, int indentLevel, StringBuilder sb) {
        scopes.push(new HashMap<>());
        List<Stmt> statements = block.statements();
        if (statements.isEmpty()) {
            indent(indentLevel, sb);
            sb.append("pass\n");
        }
        for (Stmt stmt : statements) {
            genStmt(stmt, indentLevel, sb);
        }
        scopes.pop();
    }

    private String genExpr(Expr expr) {
        return switch (expr) {
            case NumberLiteral n -> n.isFloat() ? String.valueOf(n.floatValue()) : String.valueOf(n.intValue());
            case StringLiteral s -> pythonStringLiteral(s.value());
            case IdentifierExpr id -> resolve(id.name());
            case UnaryExpr u -> u.op() == UnaryOp.NOT
                    ? "(not " + genExpr(u.operand()) + ")"
                    : "(" + (u.op() == UnaryOp.NEG ? "-" : "+") + genExpr(u.operand()) + ")";
            case BinaryExpr b ->
                    "(" + genExpr(b.left()) + " " + pythonOperator(b) + " " + genExpr(b.right()) + ")";
        };
    }

    // The one operator that is not a straight translation: Ankur's `/` between two পূর্ণ
    // values truncates, like Java's int division, while Python's `/` always produces a float.
    private String pythonOperator(BinaryExpr b) {
        if (b.op() == BinaryOp.DIV && types.get(b) == Type.INT) {
            return "//";
        }
        return switch (b.op()) {
            case ADD -> "+";
            case SUB -> "-";
            case MUL -> "*";
            case DIV -> "/";
            case MOD -> "%";
            case EQ -> "==";
            case NEQ -> "!=";
            case LT -> "<";
            case GT -> ">";
            case LE -> "<=";
            case GE -> ">=";
            case AND -> "and";
            case OR -> "or";
        };
    }

    private static String pythonStringLiteral(String value) {
        StringBuilder sb = new StringBuilder("\"");
        for (char c : value.toCharArray()) {
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                case '\t' -> sb.append("\\t");
                default -> sb.append(c);
            }
        }
        return sb.append('"').toString();
    }

    private static String defaultValue(VarType type) {
        return switch (type) {
            case PURNO -> "0";
            case DOSHOMIK -> "0.0";
            case BAKKO -> "\"\"";
        };
    }

    // Only a genuine shadow -- this name already resolving to something on an ENCLOSING scope
    // currently on the stack -- gets renamed. Python has no block scope of its own, so a name
    // that merely repeats in an unrelated sibling block (an if-branch and its else, say) is
    // never a real collision: only one branch's assignment ever runs, and it keeps its bare
    // Ankur name -- which is the ordinary case, so the generated Python reads like the source.
    private String declare(String ankurName) {
        String pythonName = resolveOrNull(ankurName) != null
                ? ankurName + "_" + (nameCounter++)
                : ankurName;
        scopes.peek().put(ankurName, pythonName);
        return pythonName;
    }

    private String resolve(String ankurName) {
        String found = resolveOrNull(ankurName);
        if (found != null) {
            return found;
        }
        throw new IllegalStateException(
                "Unresolved identifier '" + ankurName + "' during code generation "
                        + "(the program should have been validated by SemanticAnalyzer first)");
    }

    private String resolveOrNull(String ankurName) {
        for (Map<String, String> scope : scopes) {
            String found = scope.get(ankurName);
            if (found != null) {
                return found;
            }
        }
        return null;
    }

    private static void indent(int level, StringBuilder sb) {
        sb.append("    ".repeat(level));
    }
}
